### ISSUE TITLE
Improve benchmarking suite

### ISSUE THREAD

**Issue by maleadt** [JuliaGPU/CUDA.jl#222]
- add benchmarks
- `tune!`, and cache those results (requires changes to gitlab v6.yml, adding a `cache` dir)

**Comment by maleadt** [comment]
Just ran into those two errors:

```
app_1  | Internal Server Error: /result/add/json/
app_1  | Traceback (most recent call last):
app_1  |   File "./codespeed/results.py", line 76, in save_result
app_1  |     rev = branch.revisions.get(commitid=data['commitid'])
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
app_1  |     return getattr(self.get_queryset(), name)(*args, **kwargs)
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 399, in get
app_1  |     self.model._meta.object_name
app_1  | codespeed.models.Revision.DoesNotExist: Revision matching query does not exist.
app_1  | 
app_1  | During handling of the above exception, another exception occurred:
app_1  | 
app_1  | Traceback (most recent call last):
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
app_1  |     response = get_response(request)
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
app_1  |     response = self.process_exception_by_middleware(e, request)
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
app_1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
app_1  |     return view_func(*args, **kwargs)
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/views/decorators/http.py", line 40, in inner
app_1  |     return func(request, *args, **kwargs)
app_1  |   File "./codespeed/auth.py", line 57, in _decorator
app_1  |     return func(request, *args, **kwargs)
app_1  |   File "./codespeed/views.py", line 921, in add_json_results
app_1  |     response, error = save_result(result, update_repo=(i==0))
app_1  |   File "./codespeed/results.py", line 90, in save_result
app_1  |     commit_logs = commits.get_logs(rev, rev, update=update_repo)
app_1  |   File "./codespeed/commits/logs.py", line 29, in get_logs
app_1  |     logs = getlogs(rev, startrev)
app_1  |   File "./codespeed/commits/github.py", line 157, in getlogs
app_1  |     revision.commitid, username, project, revision)
app_1  |   File "./codespeed/commits/github.py", line 115, in retrieve_revision
app_1  |     revision.full_clean()
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 1152, in full_clean
app_1  |     raise ValidationError(errors)
app_1  | django.core.exceptions.ValidationError: {'__all__': ['Revision with this Commitid and Branch already exists.']}
```


```
app_1  | Internal Server Error: /result/add/json/
app_1  | Traceback (most recent call last):
app_1  |   File "./codespeed/results.py", line 76, in save_result
app_1  |     rev = branch.revisions.get(commitid=data['commitid'])
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
app_1  |     return getattr(self.get_queryset(), name)(*args, **kwargs)
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 399, in get
app_1  |     self.model._meta.object_name
app_1  | codespeed.models.Revision.DoesNotExist: Revision matching query does not exist.
app_1  | 
app_1  | During handling of the above exception, another exception occurred:
app_1  | 
app_1  | Traceback (most recent call last):
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
app_1  |     response = get_response(request)
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
app_1  |     response = self.process_exception_by_middleware(e, request)
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
app_1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
app_1  |     return view_func(*args, **kwargs)
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/views/decorators/http.py", line 40, in inner
app_1  |     return func(request, *args, **kwargs)
app_1  |   File "./codespeed/auth.py", line 57, in _decorator
app_1  |     return func(request, *args, **kwargs)
app_1  |   File "./codespeed/views.py", line 921, in add_json_results
app_1  |     response, error = save_result(result, update_repo=(i==0))
app_1  |   File "./codespeed/results.py", line 90, in save_result
app_1  |     commit_logs = commits.get_logs(rev, rev, update=update_repo)
app_1  |   File "./codespeed/commits/logs.py", line 29, in get_logs
app_1  |     logs = getlogs(rev, startrev)
app_1  |   File "./codespeed/commits/github.py", line 157, in getlogs
app_1  |     revision.commitid, username, project, revision)
app_1  |   File "./codespeed/commits/github.py", line 115, in retrieve_revision
app_1  |     revision.full_clean()
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 1152, in full_clean
app_1  |     raise ValidationError(errors)
app_1  | django.core.exceptions.ValidationError: {'__all__': ['Revision with this Commitid and Branch already exists.']}
```
